version: "2.2"

services:
  jupyterlab:
    build: jupyterlab-slurm/slurm_cluster/jupyterlab/.
    hostname: jupyterlab
    volumes:
      - ./jupyterlab-slurm:/usr/local/jupyterlab-slurm/
      - etc_munge:/etc/munge:ro
    depends_on:
      - slurmctld
    ports:
      - "61888:8888"

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    ports:
      - "63306:3306"

  slurmdbd:
    image: slurm-docker-cluster:19.05.1
    command: ["slurmdbd"]
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    ports:
      - "61819:6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:19.05.1
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    ports:
      - "61817:6817"
    depends_on:
      - slurmdbd

  c1:
    image: slurm-docker-cluster:19.05.1
    command: ["slurmd"]
    hostname: c1
    volumes:
      - etc_munge:/etc/munge:ro
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    ports:
      - "61814:6818"
    depends_on:
      - slurmctld

  c2:
    image: slurm-docker-cluster:19.05.1
    command: ["slurmd"]
    hostname: c2
    volumes:
      - etc_munge:/etc/munge:ro
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    ports:
      - "61815:6818"
    depends_on:
      - slurmctld

volumes:
  etc_munge:
  run_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  jupyterlab-slurm:
