name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install node
      uses: actions/setup-node@v4
      with:
       node-version: 18
       cache: 'yarn'
       cache-dependency-path: yarn.lock
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
    - name: Install the extension
      run: python -m pip install .
    - name: Update markupsafe
      run: python -m pip install markupsafe==2.0.1
    - name: Check the extension
      run: |
        jlpm
        jlpm run eslint:check
        RED=`tput -T xterm setaf 1`
        GREEN=`tput -T xterm setaf 2`
        SERVER_EXT=`jupyter serverextension list 2>&1`
        LAB_EXT=`jupyter labextension list 2>&1`
        echo -n "server extension install "
        grep -e "jupyterlab_slurm.*OK" <<< $SERVER_EXT && echo "${GREEN}PASS" || echo "${RED}FAIL"
        echo "$SERVER_EXT"
        echo -n "lab extension install "
        grep -e "jupyterlab-slurm.*enabled.*OK" <<< $LAB_EXT && echo "${GREEN}PASS" || echo "${RED}FAIL"
        echo "$LAB_EXT"